=begin
This is my solution to Project Euler Problem 2.
Instructions:
Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four 
million, find the sum of the even-valued terms.
=end

fib_nums = [1,2] # first two terms
maximum = 4000000
total = 0

# this loop adds fibonacci numbers to array 
# note that the last item is higher than the maximum (resolved in next loop)
while fib_nums[fib_nums.length-1] < maximum
	fib_nums[fib_nums.length] = fib_nums[fib_nums.length-1] + fib_nums[fib_nums.length-2]
end

# this loop adds the even fibonacci numbers to the running total, 
# and excludes the last number, which is over the maximum
for num in fib_nums
	if num % 2 == 0 && num < maximum
		total += num
	end
end

puts total # answer is 4,613,732